# Setup
title:        david barber
tagline:      machine learning
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       David Barber
  url:        http://www0.cs.ucl.ac.uk/people/D.Barber.html

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown